# Generated by Django 3.1.7 on 2021-04-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='num_orden',
            field=models.CharField(default='', max_length=20),
        ),
    ]
