# Generated by Django 3.1.7 on 2021-05-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0002_auto_20210423_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clientesapp.cliente'),
        ),
    ]
