# Generated by Django 3.2.3 on 2021-05-26 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0005_auto_20210513_1442'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orden',
            table=None,
        ),
    ]
